services:
  sync-worker:
    container_name: mealie-firebase-bridge
    build:
      context: ../
      dockerfile: ./services/sync-worker/Dockerfile
    restart: always
    environment:
      - MEALIE_API_URL=http://mealie:9000
      - MEALIE_API_TOKEN=${MEALIE_API_TOKEN}
      - FIREBASE_SERVICE_ACCOUNT_JSON=/app/data/firebase_service_account.json
    volumes:
      - mealie-data:/app/data/
    depends_on:
      - mealie

volumes:
  mealie-data:
    external: true
