services:
  mealie:
    container_name: mealie
    image: ghcr.io/jaredgriffiths/mealie:latest
    build:
      context: ../
      target: production
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "9925:9000"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - /srv/dev-disk-by-uuid-9800de14-df33-4684-904e-16c9c372cae9/media/mealie/data:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 100
      TZ: Australia/Victoria
      BASE_URL: http://192.168.50.107:9925
